project_id = "aliqjghojatlklyvcurs"

[functions.generate-model]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-product-checkout]
verify_jwt = true

[functions.buy-credits]
verify_jwt = true

