project_id = "khdczrzplqssygwoyjte"

[functions.generate-model]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-product-checkout]
verify_jwt = false

[functions.buy-credits]
verify_jwt = true

[functions.subscribe-newsletter]
verify_jwt = false

[functions.contact]
verify_jwt = false
